patience: 5

dataloader_args:
  batch_size: 200
  drop_last: true
  num_workers: 16
  pin_memory: false
  prefetch_factor: 8

loss: CrossEntropyLoss
loss_args: {}

model: xvector

num_epochs: 10

optimizer: Adam
optimizer_args:
  lr: 0.001
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0
  amsgrad: false

